### ISSUE TITLE
Cannot discover La Capitaine Folder colors 

### ISSUE THREAD

**Issue by alex285** [bil-elmoussaoui/nautilus-folder-icons#14]
as you can see from the image..
![screenshot from 2018-02-01 10-20-00](https://user-images.githubusercontent.com/11244308/35668294-9e8e9e78-0739-11e8-9510-f1902be619ab.png)

that was used to work before, so i guess is some change on La Capitaine icon set
https://github.com/keeferrourke/la-capitaine-icon-theme

**Comment by alex285** [comment]
hmm, i think it is a different issue. it gives me that error (Ubuntu 18,04)

```
(nautilus:13449): Gtk-WARNING **: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
Traceback (most recent call last):
  File "/usr/share/nautilus-folder-icons/icons_select.py", line 117, in do_loaded
    child = FolderBox(folder)
  File "/usr/share/nautilus-folder-icons/icons_select.py", line 39, in __init__
    self._build_widget()
  File "/usr/share/nautilus-folder-icons/icons_select.py", line 47, in _build_widget
    pixbuf = theme.load_icon(self.name, 64, 0)
GLib.Error: gdk-pixbuf-error-quark: Failed to load /usr/share/icons/la-capitaine-icon-theme/places/scalable/folder-image.svg: Unrecognized image file format (3)
```

**Comment by bilelmoussaoui** [comment]
Fixed on master
