### ISSUE TITLE
Namespace %s is already loaded with version %s

### ISSUE THREAD

**Issue by coffandro** [bil-elmoussaoui/nautilus-folder-icons#41]
Here's the error
```cornelius@fedora:~/theming/nautilus-folder-icons$ nautilus
** Message: 09:44:04.935: Connecting to org.freedesktop.Tracker3.Miner.Files

(org.gnome.Nautilus:21113): Gtk-WARNING **: 09:44:05.069: Unknown key gtk-modules in /home/cornelius/.config/gtk-4.0/settings.ini
GSConnect: [Errno 2] No translation file found for domain: 'org.gnome.Shell.Extensions.GSConnect'
kdeconnect-nautilus: [Errno 2] No translation file found for domain: 'kdeconnect-nautilus-extension'
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/folder-icons.py", line 26, in <module>
    require_version("Gtk", "3.0")
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/site-packages/gi/__init__.py", line 113, in require_version
    raise ValueError('Namespace %s is already loaded with version %s' %
                     (namespace, loaded_version))
ValueError: Namespace Gtk is already loaded with version 4.0
Initialized Nautilus Applications extension
^C
(org.gnome.Nautilus:21113): Gdk-WARNING **: 09:45:17.568: ../gdk/wayland/gdkcursor-wayland.c:210 cursor image size (32) not an integer multiple of theme size (24)
Traceback (most recent call last):
  File "/home/cornelius/.local/share/nautilus-python/extensions/NautilusApplications/NautilusApplications.py", line 73, in get_file_items
    def get_file_items(
    
KeyboardInterrupt

(org.gnome.Nautilus:21113): Gdk-WARNING **: 09:45:18.353: ../gdk/wayland/gdkcursor-wayland.c:210 cursor image size (32) not an integer multiple of theme size (24)```

**Comment by coffandro** [comment]
seems to be due to nautilus python v3 vs v4

**Comment by coffandro** [comment]
#20 might fix it?

**Comment by coffandro** [comment]
Tried just relabeling all "Require("gtk/gdk/nautilus", "3.0")" to Require("gtk/gdk/nautilus", "4.0" )".
and it seems the project is using API's that no longer exist, like LocationWidgetProvider.

https://gnome.pages.gitlab.gnome.org/nautilus-python/nautilus-python-migrating-to-4.html

**Comment by bilelmoussaoui** [comment]
Yes it would need more changes. Patches are welcome.
